# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: nmandakh <nmandakh@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/03/02 18:00:10 by nmandakh          #+#    #+#              #
#    Updated: 2024/03/02 18:02:28 by nmandakh         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# Compiler & Flags
CC		=	cc
CFLAGS	=	-Wall -Werror -Wextra -g

# Targets
C_SRCS	=	client.c
S_SRCS	=	server.c
LIBFT		=	./lib/Libft/libft.a
FT_PRINTF	=	./lib/ft_printf/libftprintf.a

# Program names
CLIENT	=	client
SERVER	=	server

# Compilation
